apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.ObjectMeta.Name}}
  namespace: {{.ObjectMeta.Namespace}}
spec:
  rules:
  - host: {{.ObjectMeta.Name}}.john.tech
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{.ObjectMeta.Name}}
            port: 
              number: 8080
